### ISSUE TITLE
Get the response headers

### ISSUE THREAD

**Issue by mikelgmh** [KenEucker/imgur#185]
**Is your feature request related to a problem? Please describe.**
I need a way to know when I hit the [rate limits](https://api.imgur.com/#limits). 

**Describe the solution you'd like**
We can check the credits available by looking at the headers (`X-RateLimit-UserRemaining`). Check the link I left above.

**Describe alternatives you've considered**
The only way to do this right now is using the Imgur api without this npm package.

**Additional context**
That's all!

**Comment by KenEucker** [comment]
@mikelgmh how would you expect to get access to this? 

I think the fetcher (axios) is exposed. Maybe you can access it and get what you need?

**Comment by KevinNovak** [comment]
I'm also looking to see the response headers so I can avoid the Imgur API's rate limits. I tried looking at the fetcher (ImgurClient#fetcher) like @KenEucker suggested but couldn't find anything. I may end up just manually calling the Imgur API instead so I can see the full response.

**Comment by KenEucker** [comment]
@KevinNovak if you want to pair on this I'd be happy to understand the problem better.

**Comment by KevinNovak** [comment]
Sure, so for free account Imgur has a limit of ~1,250 image uploads per day (this is an approximate number, since the Imgur API is actually using a credit system where you get a certain number of credits per day, and different Imgur API actions use a different amount of credits).

If you try to upload an image after the daily limit is reached, Imgur will respond with 429 status code, blocking the request.

In every response header, Imgur includes the [following values](https://api.imgur.com/#limits):
- `X-RateLimit-UserLimit` - Total credits that can be allocated.
- `X-RateLimit-UserRemaining` - Total credits available.
- `X-RateLimit-UserReset` - Timestamp (unix epoch) for when the credits will be reset.
- `X-RateLimit-ClientLimit` - Total credits that can be allocated for the application in a day.
- `X-RateLimit-ClientRemaining` - Total credits remaining for the application in a day.

These can checked by the application (or potentially this package) to avoid sending a request if it would exceed the daily credit limit, however this package doesn't expose the headers in the result of `ImgurClient#upload`.

One way this could be fixed, by just exposing these headers in the response of `Utils#getImgurApiResponseFromResponse()`:

```typescript
  if (typeof response === 'undefined') {
    data = 'response was empty';
    status = 500;
    success = false;
  } else if (typeof response === 'string') {
    data = response as string;
    status = 500;
    success = false;
  } else if (responseIsSuccess) {
    status = response.data.status;
    data = response.data.data.error
      ? response.data.data.error
      : response.data.data;
    headers = response.headers; // Save response headers
  } else {
    success = false;
    status =
      response.data.data?.error?.code ??
      response.status ??
      response.data.status;
    headers = response.headers; // Save response headers
    data = getResponseData(
      responseIsError
        ? response.data.errors ??
            response.data.data.error.message ??
            response.data.data.error
        : response.data.data ?? response.data.message ?? response.data
    );
  }

  return {
    data,
    headers, // Return response headers
    status,
    success,
  };
```

**Comment by KenEucker** [comment]
@KevinNovak yeah, go ahead and create a PR for that and we can maybe work together on a solution for the rate limit that you are running into.

**Comment by KevinNovak** [comment]
Will work on it later today. What branch would you like me to target, "develop"?

**Comment by KenEucker** [comment]
@KevinNovak yup, PR to develop and then releases are handled from develop to main.
